version: '3.8'
services:
  scraper:
    container_name: scraper
    build:
      context: ./
    image: scraper
    network_mode: host
    restart: always
    volumes:
    - ./database_news.sqlite3:/database_news.sqlite3